#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP_NAME="$1"

APP="$1"; shift
INTERNAL_PORT="$1"; shift
INTERNAL_IP_ADDRESS="$1"; shift

case "$APP" in
  dns)
    sudo iptables -t nat -I PREROUTING 2 -i eth0 -p tcp --dport 53 -j REDIRECT --to-port $INTERNAL_PORT
    sudo iptables -t nat -I PREROUTING 2 -i eth0 -p udp --dport 53 -j REDIRECT --to-port $INTERNAL_PORT
  ;;
esac
